# Generated by Django 4.0.3 on 2022-04-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creator',
            new_name='user',
        ),
    ]
